name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Discord notification
  env:
    DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  uses: burntdragon/Precious/
  with:
    args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.'
